### PR TITLE
Implement GSA line

### LINKED ISSUE #6: Parse GSA line
$GPGSA,A,3,04,05,,09,12,,,24,,,,,2.5,1.3,2.1*39

Where:
     GSA      Satellite status
     A        Auto selection of 2D or 3D fix (M = manual) 
     3        3D fix - values include: 1 = no fix
                                       2 = 2D fix
                                       3 = 3D fix
     04,05... PRNs of satellites used for fix (space for 12) 
     2.5      PDOP (dilution of precision) 
     1.3      Horizontal dilution of precision (HDOP) 
     2.1      Vertical dilution of precision (VDOP)
     *39      the checksum data, always begins with *

### PR DESCRIPTION
**Pull request by helluvamatt**
Fixes #6

### CODE REVIEW

**Comment by DemetriouJohn** [comment]
Apologies my friend, you did not reply in time so I handled it myself

**Comment by DemetriouJohn** [comment]
Feel free to assign issues to yourself next time before taking them so we can better coordinate

**Comment by DemetriouJohn** [comment]
Also, feel free to create new issues if you fee like something is missing

**Comment by helluvamatt** [comment]
Oops, sorry about that. I'll assign myself issues that I'd like to tackle.

**Pull request closed without merging**
